---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wayfowar/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp footer.html $DEPLOYPATH
    - /bin/cp header.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp afmh.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp gallery-slider.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH